config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
  			path: '',
  			path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
  			controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users, only: [:show]
  resources :skills, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'perks'
      get 'location'
      get 'preload'
      get 'preview'
    end

  resources :photos, only: [:create, :destroy]
  resources :reservations, only: [:create]
  end
  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]
  
  get '/your_hirings' => 'reservations#your_trips'
  get '/your_costumers' => 'reservations#your_reservations'
  get 'search' => 'pages#search'
  get '/policy' => 'pages#policy'
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user
  has_many :photos
  has_many :reservations
  has_many :guest_reviews

  geocoded_by :portfolio
  after_validation :geocode, if: :portfolio_changed?

  validates :category_type, presence: true
  validates :skill_type, presence: true
  validates :day_hour, presence: true

  def cover_photo(size)
  	if self.photos.length > 0
  		self.photos[0].image.url(size)
  	else
  		"default.jpg"
  	end
  end

  def average_rating
    guest_reviews.count == 0 ? 0 : guest_reviews.average(:star).round(2).to_i
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :is_authorized, only: [:listing, :pricing, :description, :photo_upload, :perks, :location, :update]
  def index
    @skills = current_user.skills
  end

  def new
    @skill = current_user.skills.build
  end

  def create
    @skill = current_user.skills.build(skill_params)
    if @skill.save
      redirect_to listing_skill_path(@skill), notice: "Saved..."
    else
      flash[:alert] = @skill.errors.full_messages[0]
      render :new 
    end
  end

  def show
    @photos = @skill.photos
    @guest_reviews = @skill.guest_reviews
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
    @photos = @skill.photos
  end

  def perks
  end

  def location
  end

  def update
    new_params = skill_params
    new_params = skill_params.merge(active: true) if is_ready_skill

    if @skill.update(new_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Something went wrong..."
    end
    redirect_back(fallback_location: request.referer)
  end

  # --- Reservations ---
  def preload
    today = Date.today
    reservations = @skill.reservations.where("start_date >= ? OR end_date >= ?", today, today)

    render json: reservations
  end

  def preview
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    output = {
      conflict: is_conflict(start_date, end_date, @skill)
    }

    render json: output
  end

  private
    def is_conflict(start_date, end_date, skill)
      check = skill.reservations.where("? < start_date AND end_date < ?", start_date, end_date)
      check.size > 0? true : false
    end

    def set_skill
      @skill = Skill.find(params[:id])
    end

    def is_ready_skill
      !@skill.active && !@skill.price.blank? && !@skill.skill_name.blank? && !@skill.photos.blank? && !@skill.portfolio.blank?
    end

    def is_authorized
      redirect_to root_path, alert: "You don't have permission to do that!" unless current_user.id == @skill.user_id
    end

    def skill_params
      params.require(:skill).permit(:category_type, :skill_type, :perk, :day_hour, :skill_name, :summary, :portfolio, :is_skype,
        :is_ip,:is_discord,:is_steam,:is_fi,:price, :active, :address)
    end
end

app/helpers/skill_helper.rb
module SkillHelper
end

app/views/skills/_skill_menu.html.erb
<ul class="sidebar-list">
	<li class="sidebar-item">
	<%= link_to "Listing", listing_skill_path, class: "sidebar-link active" %>
	<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
	</li>

	<li class="sidebar-item">
	<%= link_to "Pricing", pricing_skill_path, class: "sidebar-link active" %>
	<%if !@skill.price.blank? %>
	<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
	<% end %>
	</li>

	<li class="sidebar-item">
	<%= link_to "Description", description_skill_path, class: "sidebar-link active" %>
	<%if !@skill.skill_name.blank? %>
	<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
	<% end %>
	</li>

	<li class="sidebar-item">
	<%= link_to "Photos", photo_upload_skill_path, class: "sidebar-link active" %>
	<%if !@skill.photos.blank? %>
	<span id="photo_check" class="pull-right text-babu"><i class="fa fa-check"></i></span>
	<% end %>
	</li>

	<li class="sidebar-item">
	<%= link_to "Perks", perks_skill_path, class: "sidebar-link active" %>
	<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
	</li>

	<li class="sidebar-item">
	<%= link_to "Location", location_skill_path, class: "sidebar-link active" %>
	<%if !@skill.portfolio.blank? %>
	<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
	<% end %>
	</li>
</ul>
<br/>

<% is_ready = !@skill.active && !@skill.price.blank? && !@skill.skill_name.blank? && !@skill.photos.blank? && !@skill.portfolio.blank? %>

<%= form_for @skill do |f| %>
	<%= f.hidden_field :active, value: true %>
	<%= f.submit "Publish", id: "publish_button", class: "btn btn-normal btn-block", disabled: !is_ready %>
<% end %>

app/views/skills/_skills_list.html.erb
<% skills.each do |skill| %>
		<div class="col-md-4">
			<div class="panel panel-default">
					<div class="panel-heading preview">
						<%= image_tag skill.cover_photo(:medium) %>
					</div>

					<div class="panel-body">
						<%= link_to skill.skill_name, skill %><br/>
						<%= skill.category_type %> - <%= pluralize(skill.day_hour, "hour") %>
						<div id="star_<%= skill.id %>"></div> <%= pluralize(skill.average_rating, "review") %>
					</div>
			</div>
		</div>


<script>
 $('#star_<%= skill.id %>').raty({
	path: '/assets',
	readOnly: true,
	score: <%= skill.average_rating %>
  });
</script>

<% end %>

app/views/skills/create.html.erb
<h1>Skill#create</h1>
<p>Find me in app/views/skill/create.html.erb</p>

app/views/skills/description.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render 'skill_menu' %>
	</div>
	<div class="col-md-9">
	<div class="panel panel-default">
		<div class="panel-heading">
			Description
		</div>

		<div class="panel-body">
			<div class="container">
			<%= form_for @skill do |f| %>
				<div class="row">
					<div class="form-group">
					<label>Skill name</label>
					<%= f.text_field :skill_name, placeholder: "What are you offering?", class: "form-control", required: true %>
					</div>
				</div>

				<div class="row">
					<div class="form-group">
					<label>Summary</label>
					<%= f.text_area :summary, placeholder: "A summary of what are you offering.", class: "form-control", required: true %>
					</div>
				</div>

				<div class="text-center">
					<%= f.submit "Save", class: "btn btn-form" %>
				</div>
			<% end %>
			</div>
		</div>

	</div>
	</div>
</div>

app/views/skills/index.html.erb
<div class="row">
	<div class="col-md-3">
		<ul class="sidebar-list">
			<li class="sidebar-item"><%= link_to "Your Listings", skills_path, class: "sidebar-link active" %></li>
			<li class="sidebar-item"><%= link_to "Your Costumers", your_costumers_path, class: "sidebar-link" %></li>
			<li class="sidebar-item"><%= link_to "Your Hirings", your_hirings_path, class: "sidebar-link" %></li>
		</ul>
	</div>

	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Listings
			</div>
			<div class="panel-body">
				<% @skills.each do |skill| %>
					<div class="row">
						<div class="col-md-2">
							<%= image_tag skill.cover_photo(:thumb) %>
						</div>
						<div class="col-md-7">
							<h4><%= skill.skill_name %></h4>
						</div>
						<div class="col-md-3 right">
							<%= link_to "Update", listing_skill_path(skill), class: "btn btn-form" %>
						</div>
					</div>
						<br/>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/skills/listing.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render 'skill_menu' %>
	</div>
	<div class="col-md-9">
	<div class="panel panel-default">
		<div class="panel-heading">
			Listing
		</div>

		<div class="panel-body">
			<div class="container">
					<%= form_for @skill do |f| %>

			<div class="row">
				<div class="col-md-4 select">
				<div class="form-group">
					<label>Skill Category</label>
					<%= f.select :category_type, [["Gaming","Gaming"],["Art & Design","Art & Design"],["Social Media","Social Media"]],
					id: "category_type", promt: "Select...", class: "form-control" %>
					</div>
				</div>

				<div class="col-md-4 select">
				<div class="form-group">
					<label>Purpose</label>
					<%= f.select :skill_type, [["Improvement","Improvement"],["Basics","Basics"],["Free Time","Free Time"],["Problem-solving","Problem-solving"]],
					id: "skill_type", promt: "Select...", class: "form-control" %>
					</div>
				</div>

				<div class="col-md-4 select">
				<div class="form-group">
					<label>Duration</label>
					<%= f.select :day_hour, [["4 Hours","4 Hours"],["6 Hours","6 Hours"],["8 Hours","8 Hours"]],
					id: "day_hour", promt: "Select...", class: "form-control" %>
					</div>
				</div>

			</div>

			<div><%= f.submit "Save", class: "btn btn-normal" %></div>

		<% end %>
			</div>
		</div>

	</div>
	</div>
</div>

app/views/skills/location.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render 'skill_menu' %>
	</div>
	<div class="col-md-9">
	<div class="panel panel-default">
		<div class="panel-heading">
			Location
		</div>

		<div class="panel-body">
			<div class="container">
				<%= form_for @skill do |f| %>
				<div class="row">
					<div class="form-group">
					<label>Where are you from?</label>
					<%= f.text_field :portfolio, placeholder: "eg: Los Angeles, California", class: "form-control", required: true, id: "autoaddress"%>
					</div>
				</div>

				<div class="text-center">
					<%= f.submit "Save", class: "btn btn-form" %>
				</div>
				<% end %>
			</div>
		</div>

	</div>
	</div>
</div>

<script>
	 $(function() {
    $("#autoaddress").geocomplete();
  })
</script>

app/views/skills/new.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		Suprise us with your skill!
	</div>
	<div class="panel-body">
		<div class="container">
		<%= form_for @skill do |f| %>

			<div class="row">
				<div class="col-md-4 select">
				<div class="form-group">
					<label>Skill Category</label>
					<%= f.select :category_type, [["Gaming","Gaming"],["Art & Design","Art & Design"],["Social Media","Social Media"]],
					id: "category_type", promt: "Select...", class: "form-control" %>
					</div>
				</div>

				<div class="col-md-4 select">
				<div class="form-group">
					<label>Purpose</label>
					<%= f.select :skill_type, [["Improvement","Improvement"],["Basics","Basics"],["Free Time","Free Time"],["Problem-solving","Problem-solving"]],
					id: "skill_type", prompt: "Select...", class: "form-control" %>
					</div>
				</div>

				<div class="col-md-4 select">
				<div class="form-group">
					<label>Duration</label>
					<%= f.select :day_hour, [["4 Hours","4 Hours"],["6 Hours","6 Hours"],["8 Hours","8 Hours"]],
					id: "day_hour", prompt: "Select...", class: "form-control" %>
					</div>
				</div>

			</div>

			<div><%= f.submit "Submit", class: "btn btn-normal" %></div>

		<% end %>

		</div>
	</div>
</div>

app/views/skills/perks.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render 'skill_menu' %>
	</div>
	<div class="col-md-9">
	<div class="panel panel-default">
		<div class="panel-heading">
			Perks
		</div>

		<div class="panel-body">
			<div class="container">
				<%= form_for @skill do |f| %>

					<div class="row form-group">
						<div class="col-md-4">
							<%= f.check_box :is_skype %> Skype
						</div>
						<div class="col-md-4">
							<%= f.check_box :is_discord %> Discord Server
						</div>
						<div class="col-md-4">
							<%= f.check_box :is_steam %> Steam VoiceChat
						</div>
					
					</div>

					<div class="row form-group">
						<div class="col-md-4">
							<%= f.check_box :is_ip %> Meet In Person
						</div>
						<div class="col-md-4">
							<%= f.check_box :is_fi %> Freebies
						</div>
					</div>

					<br/><br/>

					<div class="text-center">
						<%= f.submit "Save", class: "btn btn-form" %>
					</div>
				<% end %>
			</div>
		</div>

	</div>
	</div>
</div>

app/views/skills/photo_upload.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render 'skill_menu' %>
	</div>
	<div class="col-md-9">
	<div class="panel panel-default">
		<div class="panel-heading">
			Photos
		</div>

		<div class="panel-body">
			<div class="container">
				<div class="row">
					<div class="col-md-offset-3 col-md-6">
						<!-- PHOTOS UPLOAD GOES HERE -->
						<%= form_for @skill, url: skill_photos_path(@skill), method: 'post', html: {multipart: true} do |f| %>
						<div class="row">
							<div class="form-group">
								<span class="btn btn-default btn-file text-babu">
								<i class="fa fa-picture-o" aria-hidden="true"></i> Select Photos
									<%= file_field_tag "images[]", type: :file, multiple: true %>
								</span>
							</div>
						</div>

						<div class="text-center">
							 <%= f.button'<i class="fa fa-cloud-upload" aria-hidden="true"></i>  UPLOAD'.html_safe, class: "btn btn-form", id: "register-button" %>


						</div>
						<% end %>
					</div>
				</div>
				<div id="photos">
					<%= render 'photos/photos_list' %>
				</div>
			</div>
		</div>

	</div>
	</div>
</div>

app/views/skills/pricing.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render 'skill_menu' %>
	</div>
	<div class="col-md-9">
	<div class="panel panel-default">
		<div class="panel-heading">
			Pricing
		</div>

		<div class="panel-body">
			<div class="container">
				<%= form_for @skill do |f| %>
				<div class="row">
					<div class="form-group">
					<label>Price</label>
					<%= f.text_field :price, placeholder: "eg: $40", class: "form-control", required: true%>
					</div>
				</div>

				<div class="text-center">
					<%= f.submit "Save", class: "btn btn-form" %>
				</div>
				<% end %>
			</div>
		</div>

	</div>
	</div>
</div>

app/views/skills/show.html.erb
<!-- image -->

<div class="row">
	<div class="col-md-12">
		<%= image_tag @skill.cover_photo(nil), width: "100%" %>
	</div>
</div>
<br/>

<div class="row">
	<!-- left panel -->
	<div class="col-md-8">
		<!-- listing name -->
		<div class="row">
			<div class="col-md-8">
				<h1><%= @skill.skill_name %></h1>
				<%= @skill.portfolio %>
			</div>
			<div class="col-md-4 text-center">
				<%= image_tag avatar_url(@skill.user), class: "img-circle avatar-large" %><br/><br/>
				<%= @skill.user.fullname %>
			</div>
		</div>
		<br/>

		<!-- Skill info -->
		   <div class="row text-babu">
		      <div class="row text-center row-space-1">
		        <div class="col-md-4">
		          <i class="fa fa-cogs fa-2x"></i>
		        </div>
		        <div class="col-md-3">
		          <i class="fa fa-wpexplorer fa-2x"></i>
		        </div>
		        <div class="col-md-3">
		          <i class="fa fa-clock-o fa-2x"></i>
		        </div>
		      </div>

		      <div class="row text-center">
		        <div class="col-md-4"><%= @skill.category_type %></div>
		        <div class="col-md-3"><%= @skill.skill_type %></div>
		        <div class="col-md-3"><%= pluralize(@skill.day_hour, "Hour") %></div>
		      </div>

		    </div>
		    <hr/>

		<!-- About -->
		<div class="row">
			<div class="col-md-12">
				<h3>Summary</h3>
				<p><%= @skill.summary %></p>
			</div>
		</div>
		<br/>

		<!-- Perks -->
		<div class="row">
			<div class="col-md-3">
				<h4>Perks</h4>
			</div>

			<div class="col-md-9">
				<div class="row">
					<div class="col-md-6">
						<ul class="perks">
							<li class="<%= 'text-line-through' if !@skill.is_skype %>">Skype</li>
							<li class="<%= 'text-line-through' if !@skill.is_discord %>">Discord Server</li>
							<li class="<%= 'text-line-through' if !@skill.is_steam %>">Steam VoiceChat</li>
						</ul>
					</div>

					<div class="col-md-6">
						<ul class="perks">
							<li class="<%= 'text-line-through' if !@skill.is_ip %>">Meet In Person</li>
							<li class="<%= 'text-line-through' if !@skill.is_fi %>">Freebies</li>
						</ul>
					</div>
				</div>
			</div>
			
		</div>
		<br/>

	<!-- Carousel -->
    <div class="row">
      <% if @photos.length > 0 %>
          <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <% @photos.each do |photo| %>
                <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
            <% end %>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner">
            <% @photos.each do |photo| %>
                <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                  <%= image_tag photo.image.url() %>
                </div>
            <% end %>
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      <% end %>

    </div>
    <hr/>

<!-- REVIEWS -->
	<div class="row">
		<div class="col-md-12">
			<h3>
				<%= pluralize(@guest_reviews.count, "Review") %>
				<span id="average_rating"></span>
			</h3>
			<div class="container">
				<div><%= render "reviews/guest_list" %></div>
			</div>
		</div>
	</div>
	<br/>
	<hr/>
<!-- GOOGLE MAP -->
    <div class="row">

      <div id="map" style="width: 100%; height: 400px"></div>

      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC-zrosfklleOYcvqm5HW-5NtjPkO7UZNg"></script>
      <script>
		function CustomMarker(latlng, map, imageSrc) {
		  this.latlng_ = latlng;
		  this.imageSrc = imageSrc;
		  // Once the LatLng and text are set, add the overlay to the map.  This will
		  // trigger a call to panes_changed which should in turn call draw.
		  this.setMap(map);
		}

		CustomMarker.prototype = new google.maps.OverlayView();

		CustomMarker.prototype.draw = function() {
		  // Check if the div has been created.
		  var div = this.div_;
		  if (!div) {
		    // Create a overlay text DIV
		    div = this.div_ = document.createElement('div');
		    // Create the DIV representing our CustomMarker
		    div.className = "customMarker"


		    var img = document.createElement("img");
		    img.src = this.imageSrc;
		    div.appendChild(img);

		    // Then add the overlay to the DOM
		    var panes = this.getPanes();
		    panes.overlayImage.appendChild(div);
		  }

		  // Position the overlay 
		  var point = this.getProjection().fromLatLngToDivPixel(this.latlng_);
		  if (point) {
		    div.style.left = point.x + 'px';
		    div.style.top = point.y + 'px';
		  }
		};

		CustomMarker.prototype.remove = function() {
		  // Check if the overlay was on the map and needs to be removed.
		  if (this.div_) {
		    this.div_.parentNode.removeChild(this.div_);
		    this.div_ = null;
		  }
		};

		CustomMarker.prototype.getPosition = function() {
		  return this.latlng_;
		};

		var map = new google.maps.Map(document.getElementById("map"), {
		  zoom: 10,
		  center: new google.maps.LatLng({lat: <%= @skill.latitude %>, lng: <%= @skill.longitude %>}),
		  mapTypeId: google.maps.MapTypeId.ROADMAP
		});

		var data = [{
		  profileImage: "<%= avatar_url(@skill.user)%>",
		  pos: {lat: <%= @skill.latitude %>, lng: <%= @skill.longitude %>},
		}]

		for (var i = 0; i < data.length; i++) {
		  new CustomMarker(new google.maps.LatLng({lat: <%= @skill.latitude %>, lng: <%= @skill.longitude %>}), map, data[i].profileImage)
		}
      </script>

    </div>
    <hr/>

    <div class="row">
     <% for skill in @skill.nearbys(15) %>
    		<% if @skill.category_type == skill.category_type %>
		          <div class="col-md-4">
		            <div class="panel panel-default">
		              <div class="panel-heading preview">
		                <%= image_tag skill.cover_photo(:medium) %>
		              </div>
		              <div class="panel-body">
		                <%= link_to skill.skill_name, skill %><br/>
		                (<%= skill.distance.round(2) %> miles away)
		              </div>
		            </div>
		          </div>
	        <% else %>
	       
			<% end %>
	    <% end %>
    </div>

  </div>


  <!-- RIGHT PANEL -->
  <div class="col-md-4">
    <!-- Reservation Form -->
    <%= render 'reservations/form' %>
  </div>
</div>

<script>
  $('#average_rating').raty({
    path: '/assets',
    readOnly: true,
    score: <%= @skill.average_rating %>
  });
</script>

app/views/skills/update.html.erb
<h1>Skill#update</h1>
<p>Find me in app/views/skill/update.html.erb</p>