config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
  			path: '',
  			path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
  			controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users, only: [:show]
  resources :skills, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'perks'
      get 'location'
      get 'preload'
      get 'preview'
    end

  resources :photos, only: [:create, :destroy]
  resources :reservations, only: [:create]
  end
  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]
  
  get '/your_hirings' => 'reservations#your_trips'
  get '/your_costumers' => 'reservations#your_reservations'
  get 'search' => 'pages#search'
  get '/policy' => 'pages#policy'
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :skill

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates_with AttachmentSizeValidator, attributes: :image, less_than: 2.megabytes
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	def create
		@skill = Skill.find(params[:skill_id])

		if params[:images]
			params[:images].each do |img|
				@skill.photos.create(image: img)
			end
			@photos = @skill.photos
			if @skill.save
				redirect_back(fallback_location: request.referer, notice: "Saved...")
			else
				redirect_back(fallback_location: request.referer, alert: "One of your photos is larger than 2 MB.")
			end
		end
	end

	def destroy
		@photo = Photo.find(params[:id])
	    @skill = @photo.skill

	    @photo.destroy
	    @photos = Photo.where(skill_id: @skill.id)

	    respond_to :js
	end
end

app/views/photos/_photos_list.html.erb
<% if @photos.count > 0 %>
  <br/><br/>

  <div class="row">
    <% @photos.each do |photo| %>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading preview">
            <%= image_tag photo.image.url() %>
          </div>
          <div class="panel-body">
            <span class="pull-right">
              <%= link_to skill_photo_path(photo.skill_id, photo), remote: true, method: :delete, data: {confirm: "Are you sure?"} do %>
                <i class="fa fa-trash-o fa-lg" aria-hidden="true"></i>
              <% end %>
            </span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/photos/destroy.js.erb
$('#photos').html("<%= j render 'photos_list' %>")
<% if @skill.photos.blank? %>
	$('#photo_check').hide();
<% end %>

<% if !@skill.active && !@skill.price.blank? && !@skill.skill_name.blank? && !@skill.photos.blank? && !@skill.portfolio.blank? %>
	$('#publish_button').attr('disabled', false);
<% else %>
	$('#publish_button').attr('disabled', true);
<% end %>